<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">

    <xacro:include filename="robot_material.xacro"/>
    <xacro:include filename="robot_params.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="gazebo_full.xacro" />


    <!-- WORLD -->


    <!-- <link name="world"/>

    <joint name="world_to_body" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="body_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-10" upper="10" effort="1000" velocity="1000"/>
    </joint> -->


    <!-- BODY -->


    <link name="body_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${b_x} ${b_y} ${b_z}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${b_x} ${b_y} ${b_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${mass_body}" x="${b_x}" y="${b_y}" z="${b_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
            
    </link>


    <!-- UPPER LEG -->


    <joint name="body_to_upper_leg" type="fixed">
        <origin xyz="0 0 -0.125" rpy="0 0 0"/>
        <parent link="body_link"/>
        <child link="upper_leg_link"/>
    </joint>


    <link name="upper_leg_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${ul_r}" length="${ul_l}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.025"/>
            <geometry>
                <cylinder radius="${ul_r}" length="${ul_l*0.1}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${mass_upper_leg}" radius="${ul_r}" length="${ul_l}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- LOWER LEG -->


    <joint name="upper_leg_to_lower_leg" type="prismatic">
        <origin xyz="0 0 -0.1" rpy="0 0 0"/>
        <parent link="upper_leg_link"/>
        <child link="lower_leg_link"/>
        <axis xyz="0 0 1"/>
            <limit lower="0" upper="0.08" effort="1000" velocity="1000"/>
            <dynamics damping="0.0" friction="0.0" spring_reference="0.0" spring_stiffness="1000.0" />
    </joint>

    <link name="lower_leg_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${ll_r}" length="${ll_l}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${ll_r}" length="${ll_l}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${mass_lower_leg}" radius="${ll_r}" length="${ll_l}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="lower_leg_link">
        <collision>
            <surface>
                <contact>
                    <ode>
                        <kp>100000.0</kp>
                    </ode>
                </contact>
            </surface>
        </collision>
    </gazebo>


    <!-- FOOT -->


    <joint name="lower_leg_to_foot" type="fixed">
        <origin xyz="0 0 -0.05" rpy="0 0 0"/>
        <parent link="lower_leg_link"/>
        <child link="foot_link"/>
    </joint>

    <link name="foot_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${f_x} ${f_y} ${f_z}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${f_x} ${f_y} ${f_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${mass_foot}" x="${f_x}" y="${f_y}" z="${f_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- FOOT CONTACT -->
    

    <joint name="foot_to_foot_contact" type="fixed">
        <parent link="foot_link"/>
        <child link="foot_contact"/>
        <origin xyz="0 0 -${f_z*0.5}"/>
    </joint>

    <link name="foot_contact">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="${fc_r}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <gazebo reference="body_link">
        <material>Gazebo/Red</material>
    </gazebo>
    

</robot>