<?xml version='1.0' encoding='UTF-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="monoped">

    <xacro:include filename="robot_material.xacro"/>
    <xacro:include filename="robot_params.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="gazebo_full.xacro" />


    <!-- BODY -->


    <link name="body_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${b_x} ${b_y} ${b_z}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${b_x} ${b_y} ${b_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${mass_body}" x="${b_x}" y="${b_y}" z="${b_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
            
    </link>


    <!-- UPPER LEG -->


    <joint name="body_to_upper_leg" type="fixed">
        <origin xyz="0 0 ${b2ul}" rpy="0 0 0"/>
        <parent link="body_link"/>
        <child link="upper_leg_link"/>
    </joint>


    <link name="upper_leg_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${ul_r}" length="${ul_l}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.025"/>
            <geometry>
                <cylinder radius="${ul_r}" length="${ul_l*0.1}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${mass_upper_leg}" radius="${ul_r}" length="${ul_l}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- LOWER LEG -->


    <joint name="upper_leg_to_lower_leg" type="prismatic">
        <origin xyz="0 0 ${ul2ll}" rpy="0 0 0"/>
        <parent link="upper_leg_link"/>
        <child link="lower_leg_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="0.08" effort="200" velocity="10"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="lower_leg_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${ll_r}" length="${ll_l}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${ll_r}" length="${ll_l}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${mass_lower_leg}" radius="${ll_r}" length="${ll_l}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- PASSSIVE LOWER LEG -->


    <joint name="lower_leg_to_passive_lower_leg" type="prismatic">
        <origin xyz="0 0 ${ul2ll}" rpy="0 0 0"/>
        <parent link="lower_leg_link"/>
        <child link="passive_lower_leg"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="0.1" effort="1000" velocity="1000"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="passive_lower_leg">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${ll_r}" length="${ll_l}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <xacro:inertial_cylinder mass="${mass_lower_leg}" radius="${ll_r}" length="${ll_l}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- FOOT -->


    <joint name="passive_lower_leg_to_foot" type="fixed">
        <origin xyz="0 0 ${ll2f}" rpy="0 0 0"/>
        <parent link="passive_lower_leg"/>
        <child link="foot_link"/>
    </joint>

    <link name="foot_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${f_x} ${f_y} ${f_z}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${f_x} ${f_y} ${f_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${mass_foot}" x="${f_x}" y="${f_y}" z="${f_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- FOOT CONTACT -->
    

    <!-- <joint name="foot_to_foot_contact" type="fixed">
        <parent link="foot_link"/>
        <child link="foot_contact"/>
        <origin xyz="0 0 -${f_z*0.5}"/>
    </joint>

    <link name="foot_contact">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="${fc_r}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link> -->
    
    <gazebo reference="upper_leg_to_lower_leg">
        <springReference>0.0</springReference>
        <springStiffness>${joint_stiffness}</springStiffness>
    </gazebo>

    <gazebo reference="lower_leg_to_passive_lower_leg">
        <springReference>0.0</springReference>
        <springStiffness>${joint_stiffness}</springStiffness>
    </gazebo>

</robot>